name: Node.js Package
#
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16    

      - name: Build package
        working-directory: ${{ github.workspace }}/modules
        run: npm test

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: zip Modules.zip ./* -r   
      - run: |
          pwd
          ls -la
          mv Modules.zip /home/runner/work/npm_publish/npm_publish/modules/          
      - run: ls -la
      - run: yarn install    
      - run: yarn publish Modules.zip
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

#   call-workflow:
#    needs: publish-gpr
#    uses: hirenrparghi/reuse/.github/workflows/myworkflow.yml@main
         
