name: Node.js Package
#
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3      
        with:
          node-version: 16
      - name: Download package
        run: |
          echo "@OWNER:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
          npm install @hirenrparghi/npm-publish@8.9.9
          ls -la
