name: Node.js Package
#
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16    

      - name: Build package
        working-directory: ${{ github.workspace }}/modules
        run: npm test

      - name: Pubish package
        run: |
            cd modules
            zip Modules.zip ./* -r
            pwd
            ls -la
            yarn install         
            yarn publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

#   call-workflow:
#    needs: publish-gpr
#    uses: hirenrparghi/reuse/.github/workflows/myworkflow.yml@main
         
