name: Node.js Package
#
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16    

      - name: Build package
        working-directory: ${{ github.workspace }}/modules
        run: npm test

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
#       - run: zip Modules.zip ./* -r   
      - run: |
          pwd
          ls -la
          cd /home/runner/work/npm_publish/npm_publish/modules
          ls -la
          yarn install
          yarn pack modules package.zip
          echo "//npm.pkg.github.com/:_authToken=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" >> ~/.npmrc
          npm publish package.zip --registry=https://npm.pkg.github.com/hirenrparghi
          


#   call-workflow:
#    needs: publish-gpr
#    uses: hirenrparghi/reuse/.github/workflows/myworkflow.yml@main
         
